% salt and pepper noise

% Type:
% which also called impulse noise, shot noise, or binary noise that is randomly scattered white or black (or
% both) pixels over the image

% Source:
% this degradation can be caused by sharp, sudden disturbances in the image
% signal; generated by errors during analog to digital conversion or data transfer

% Remove Method:
% An effective noise reduction method for this type of noise is a median filter[1] or
% a morphological filter. For reducing either salt noise or pepper noise, but not both, 
% a contraharmonic mean filter can be effective.

% add and remove noise 
im = imread('twin.tif');
% add_salt_pepper_noise
im_saltpepper = imnoise(im,'salt & pepper',0.2);
imwrite(im_saltpepper,'salt_pepper_noise.tif');
% Remove_salt_pepper_noise
% Low Pass Filter
a3=fspecial('average',[3,3]); % fspecial creates a two-dimensional filter 
im_low_saltpepper=filter2(a3,im_saltpepper);
im_low_saltpepper = uint8(im_low_saltpepper);
% Median Filtering (it seems almost tailor-made for removal of salt and pepper noise)
% recall that the median of a set is the middle value when they are sorted. If there are an even number of values, the
% median is the mean of the middle two. 
im_me_saltpeppe=medfilt2(im_saltpepper);

% plot the image
subplot(4,2,1), imshow(im),title('original_img');
subplot(4,2,2), imhist(im);
subplot(4,2,3), imshow(im_saltpepper),title('salt_pepper_noise');
subplot(4,2,4), imhist(im_saltpepper);
subplot(4,2,5), imshow(im_low_saltpepper),title('low_saltpepper');
subplot(4,2,6), imhist(im_low_saltpepper);
subplot(4,2,7), imshow(im_me_saltpeppe),title('median_filter');
subplot(4,2,8), imhist(im_me_saltpeppe);






